# IoT Gateway 规则引擎功能测试配置
# 此配置文件专门用于测试规则引擎的各种功能和性能

# 网关核心配置
gateway:
  name: "IoT Gateway Rule Engine Test"
  version: "1.0.0"
  log_level: "error"
  http_port: 8080
  https_port: 8443
  nats_url: "embedded"
  plugins_dir: "./plugins"
  enable_metrics: true
  enable_profiling: true
  
  # 热加载配置
  hot_reload:
    enabled: true                    # 启用/禁用配置文件热加载
    graceful_fallback: true          # 热加载失败时优雅降级
    retry_interval: "30s"            # 监控器启动失败后重试间隔
    max_retries: 3                   # 最大重试次数

# 规则引擎配置
rule_engine:
  enabled: true
  rules_dir: "./rules"
  subject: "iot.data.>"
  
  # 规则文件热加载配置
  hot_reload:
    enabled: true                    # 启用/禁用规则文件热加载
    graceful_fallback: true          # 热加载失败时优雅降级
    retry_interval: "30s"            # 文件监控器启动失败后重试间隔
    max_retries: 3                   # 最大重试次数
    debounce_delay: "100ms"          # 文件变更防抖延迟
  
  # 内联规则定义
#  rules:
#    - id: "temperature_alert"
#      name: "温度报警规则"
#      description: "当温度超过40度时发送报警"
#      enabled: true
#      priority: 100
#      conditions:
#        type: "and"
#        and:
#          - type: "simple"
#            field: "key"
#            operator: "eq"
#            value: "temperature"
#          - type: "simple"
#            field: "value"
#            operator: "gt"
#            value: 40
#      actions:
#        - type: "alert"
#          config:
#            level: "warning"
#            message: "设备{{.DeviceID}}温度过高: {{.Value}}°C"
#
#    - id: "humidity_monitor"
#      name: "湿度监控规则"
#      description: "监控湿度变化"
#      enabled: true
#      priority: 50
#      conditions:
#        type: "simple"
#        field: "key"
#        operator: "eq"
#        value: "humidity"
#      actions:
#        - type: "aggregate"
#          config:
#            window_type: "count"
#            size: 10
#            functions: ["avg", "max", "min"]
#            group_by: ["device_id"]
#            output_key: "{{.Key}}_stats"
#            forward: true
#
#    - id: "pressure_range_check"
#      name: "压力范围检查"
#      description: "检查压力是否在正常范围内"
#      enabled: true
#      priority: 75
#      conditions:
#        or:
#          - type: "simple"
#            field: "key"
#            operator: "eq"
#            value: "pressure"
#          - type: "simple"
#            field: "key"
#            operator: "eq"
#            value: "altitude"
#      actions:
#        - type: "filter"
#          config:
#            type: "range"
#            min: 0
#            max: 2000
#            drop_on_match: false
#        - type: "transform"
#          config:
#            field: "value"
#            type: "round"
#            precision: 1
#            add_tags:
#              validated: "true"
#
#    # 复杂数据类型规则 - GPS位置分析
#    - id: "location_analysis_rule"
#      name: "GPS位置数据分析"
#      description: "分析GPS位置数据并计算移动距离"
#      enabled: true
#      priority: 90
#      conditions:
#        type: "simple"
#        field: "key"
#        operator: "eq"
#        value: "location"
#      actions:
#        - type: "transform"
#          config:
#            field: "value.latitude"
#            type: "round"
#            precision: 6
#            output_key: "rounded_lat"
#            add_tags:
#              location_processed: "true"
#        - type: "alert"
#          config:
#            level: "warning"
#            message: "设备{{.DeviceID}}移动速度过快: {{.value.speed}}km/h"
#
#    # 复杂数据类型规则 - 3D向量幅值分析
#    - id: "vector3d_magnitude_analysis"
#      name: "3D向量幅值分析"
#      description: "分析3D向量的幅值和方向"
#      enabled: true
#      priority: 85
#      conditions:
#        type: "simple"
#        field: "key"
#        operator: "eq"
#        value: "acceleration"
#      actions:
#        - type: "transform"
#          config:
#            field: "value.magnitude"
#            type: "round"
#            precision: 3
#            output_key: "rounded_magnitude"
#            add_tags:
#              vector3d_processed: "true"
#        - type: "alert"
#          config:
#            level: "warning"
#            message: "设备{{.DeviceID}}加速度异常: {{.value.magnitude}}m/s²"
#
#    # 复杂数据类型规则 - 颜色数据分析
#    - id: "color_analysis_rule"
#      name: "颜色数据分析"
#      description: "分析RGB颜色数据"
#      enabled: true
#      priority: 70
#      conditions:
#        type: "simple"
#        field: "key"
#        operator: "eq"
#        value: "color_reading"
#      actions:
#        - type: "transform"
#          config:
#            field: "value.hue"
#            type: "round"
#            precision: 1
#            output_key: "rounded_hue"
#            add_tags:
#              color_analyzed: "true"
#        - type: "aggregate"
#          config:
#            window_type: "time"
#            window: "5m"  # 5分钟窗口
#            functions: ["avg", "max", "min"]
#            group_by: ["device_id"]
#            output_key: "color_stats"
#            forward: true
#
#    # 复杂数据类型规则 - 向量数据统计
#    - id: "vector_statistics_rule"
#      name: "向量数据统计分析"
#      description: "对向量数据进行统计分析"
#      enabled: true
#      priority: 65
#      conditions:
#        type: "simple"
#        field: "key"
#        operator: "eq"
#        value: "signal_vector"
#      actions:
#        - type: "aggregate"
#          config:
#            window_type: "count"
#            size: 10
#            functions: ["avg", "max", "min", "stddev"]
#            group_by: ["device_id"]
#            output_key: "vector_stats"
#            forward: true
#        - type: "transform"
#          config:
#            field: "value.values"
#            type: "round"
#            precision: 2
#            add_tags:
#              vector_processed: "true"
#
#    # 复杂数据类型规则 - 数组数据分析
#    - id: "array_analysis_rule"
#      name: "数组数据分析"
#      description: "对数组数据进行统计分析"
#      enabled: true
#      priority: 60
#      conditions:
#        type: "simple"
#        field: "key"
#        operator: "eq"
#        value: "measurement_array"
#      actions:
#        - type: "aggregate"
#          config:
#            window_type: "count"
#            size: 5
#            functions: ["avg", "max", "min", "p90", "p95"]
#            group_by: ["device_id"]
#            output_key: "array_stats"
#            forward: true
#        - type: "filter"
#          config:
#            type: "range"
#            field: "value.elements[0]"  # 分析第一个元素
#            min: 20.0
#            max: 80.0
#            drop_on_match: false
#
#    # 复杂数据类型规则 - 综合数据监控
#    - id: "composite_data_monitor"
#      name: "复合数据综合监控"
#      description: "监控所有复合数据类型的健康状态"
#      enabled: true
#      priority: 50
#      conditions:
#        or:
#          - type: "simple"
#            field: "key"
#            operator: "eq"
#            value: "location"
#          - type: "simple"
#            field: "key"
#            operator: "eq"
#            value: "acceleration"
#          - type: "simple"
#            field: "key"
#            operator: "eq"
#            value: "color_reading"
#          - type: "simple"
#            field: "key"
#            operator: "eq"
#            value: "signal_vector"
#          - type: "simple"
#            field: "key"
#            operator: "eq"
#            value: "measurement_array"
#      actions:
#        - type: "transform"
#          config:
#            field: "timestamp"
#            type: "format"
#            format: "2006-01-02 15:04:05"
#            output_key: "formatted_time"
#            add_tags:
#              composite_data: "true"
#              monitoring: "active"

# 南向适配器配置 - 数据源
southbound:
  adapters:
    # Mock适配器 - 用于测试
    - name: "mock_temperature_sensors"
      type: "mock"
      enabled: true
      config:
        name: "mock_temperature_sensors"
        type: "mock"
        enabled: true
        description: "温湿度传感器模拟器"
        interval: "1s"
        data_points:
          - device_id: "temp_sensor_01"
            key: "temperature"
            min_value: 15.0
            max_value: 45.0
            unit: "celsius"
          - device_id: "temp_sensor_01"
            key: "humidity"
            min_value: 30.0
            max_value: 90.0
            unit: "percent"
    
    # Mock适配器 - 压力传感器
    - name: "mock_pressure_sensors"
      type: "mock"
      enabled: true
      config:
        name: "mock_pressure_sensors"
        type: "mock"
        enabled: true
        description: "压力高度传感器模拟器"
        interval: "2s"
        data_points:
          - device_id: "pressure_sensor_01"
            key: "pressure"
            min_value: 900.0
            max_value: 1100.0
            unit: "hPa"
          - device_id: "pressure_sensor_01"
            key: "altitude"
            min_value: 0.0
            max_value: 2000.0
            unit: "meters"
    
    # Mock适配器 - 高频数据流（用于性能测试）
    - name: "mock_high_frequency"
      type: "mock"
      enabled: true
      config:
        name: "mock_high_frequency"
        type: "mock"
        enabled: true
        description: "高频振动传感器模拟器"
        interval: "100ms"
        data_points:
          - device_id: "vibration_sensor_01"
            key: "vibration"
            min_value: 0.0
            max_value: 10.0
            unit: "m/s2"
          - device_id: "vibration_sensor_01"
            key: "rotation_speed"
            min_value: 1000.0
            max_value: 5000.0
            unit: "rpm"

    # 复合数据模拟器 - 综合复合数据类型测试
    - name: "composite_mock_sensors"
      type: "composite_mock"
      enabled: true
      config:
        name: "composite_mock_sensors"
        type: "composite_mock"
        enabled: true
        description: "复合数据类型综合测试模拟器"
        interval: "3s"
        tags:
          environment: "test"
          data_source: "composite_mock"
        composite_data_types:
          # GPS位置数据
          - device_id: "gps_tracker_01"
            key: "location"
            data_type: "location"
            location_config:
              start_latitude: 39.9042
              start_longitude: 116.4074
              latitude_range: 0.01
              longitude_range: 0.01
              altitude_min: 40.0
              altitude_max: 50.0
              speed_min: 0.0
              speed_max: 60.0
              simulate_movement: true
              movement_pattern: "random_walk"
          
          # 3D向量数据（加速度计）
          - device_id: "accelerometer_01"
            key: "acceleration"
            data_type: "vector3d"
            vector3d_config:
              x_min: -10.0
              x_max: 10.0
              y_min: -10.0
              y_max: 10.0
              z_min: -10.0
              z_max: 10.0
              correlation: 0.3
              oscillation: true
              frequency: 2.0
          
          # 颜色数据（RGB传感器）
          - device_id: "rgb_sensor_01"
            key: "color_reading"
            data_type: "color"
            color_config:
              color_mode: "rainbow"
              brightness_range: [50, 255]
              saturation_range: [80, 100]
              hue_change_speed: 2.0
          
          # 通用向量数据
          - device_id: "vector_sensor_01"
            key: "signal_vector"
            data_type: "vector"
            vector_config:
              dimension: 5
              min_values: [0.0, 10.0, 20.0, 30.0, 40.0]
              max_values: [10.0, 20.0, 30.0, 40.0, 50.0]
              labels: ["ch1", "ch2", "ch3", "ch4", "ch5"]
              global_min: 0.0
              global_max: 50.0
              correlation: 0.2
              distribution: "normal"
              change_pattern: "oscillate"
              unit: "voltage"
          
          # 数组数据
          - device_id: "array_sensor_01"
            key: "measurement_array"
            data_type: "array"
            array_config:
              size: 8
              element_type: "float"
              min_value: 10.0
              max_value: 100.0
              labels: ["temp1", "temp2", "temp3", "temp4", "temp5", "temp6", "temp7", "temp8"]
              change_elements: 3
              unit: "celsius"

# 北向输出配置 - 数据目的地
northbound:
  sinks:
    # 控制台输出 - 用于调试
#    - name: "console_debug"
#      type: "console"
#      enabled: true
#      config:
#        name: "console_debug"
#        type: "console"
#        batch_size: 10
#        buffer_size: 1000
    
#    # 文件输出 - 用于数据分析
#    - name: "file_logger"
#      type: "file"
#      enabled: true
#      config:
#        filename: "./logs/rule_engine_test_data.log"
#        max_size: "100MB"
#        max_files: 10
#        format: "json"
#        include_raw_data: true
    
    # WebSocket输出 - 用于实时监控
    - name: "websocket_monitor"
      type: "websocket"
      enabled: true
      config:
        name: "websocket_monitor"
        type: "websocket"
        batch_size: 10
        buffer_size: 1000
        params:
          address: ":8092"  # 改为8092端口，避免与其他服务冲突
          path: "/ws/rules"
          allow_origins: ["*"]
          subscribe_topics:
            - "iot.rules.>"
          points: {}
    
    # MQTT输出 - 用于外部系统集成
    - name: "mqtt_output"
      type: "mqtt"
      enabled: false  # 默认禁用，需要MQTT broker
      config:
        name: "mqtt_output"
        type: "mqtt"
        batch_size: 10
        buffer_size: 1000
        params:
          broker: "tcp://localhost:1883"
          client_id: "iot_gateway_rules_test"
          topic_tpl: "iot/%s/%s"
          qos: 1
          retained: false

    - name: "rule_output_processor"
      type: "nats_subscriber"
      batch_size: 15
      params:
        buffer_size: 600
        batch_size: 30

        # 订阅规则引擎输出
        subscriptions:
          - subject: "iot.rules.>"
            data_type: "rule"
            enabled: true
            tags:
              source: "rule_engine"
              category: "processed_data"

        # 转发到WebSocket和Redis
        # 目标sink配置
        target_sinks:
          - name: "console_output"
            type: "console"
            params:
              format: "json"


# Web UI配置
web_ui:
  enabled: true
  port: 8081
  auth:
    jwt_secret: "your-secret-key-change-in-production"
    token_duration: "24h"
    refresh_duration: "168h"
    max_login_attempts: 5
    lockout_duration: "15m"
    enable_two_factor: false
    session_timeout: "30m"
    password_min_length: 6
    bcrypt_cost: 10
  
  # WebSocket配置 - 用于实时数据推送
  websocket:
    max_clients: 50        # 最大客户端连接数
    message_rate: 40       # 消息发送速率限制 (每秒) - 适应高频数据
    read_buffer_size: 4096 # 读取缓冲区大小
    write_buffer_size: 4096 # 写入缓冲区大小
    cleanup_interval: 30   # 清理间隔 (秒)
    inactivity_timeout: 300 # 不活跃超时 (秒)
    ping_interval: 54      # Ping间隔 (秒)
    pong_timeout: 60       # Pong超时 (秒)

# 数据库配置（用于存储认证信息）
database:
  sqlite:
    path: "./data/auth.db"

# Rules配置（Web服务使用）
rules:
  dir: "./rules"