gateway:
  id: "gateway-001"
  http_port: 8082
  log_level: "debug"
  nats_url: "embedded"
  plugins_dir: "./plugins"
#  metrics:
#    enabled: true
#    port: 9090

southbound:
  adapters:
    - name: "modbus-sensor"
      type: "modbus"
      config:
        name: "modbus-sensor"
        mode: "tcp"
        address: "127.0.0.1:502"
        timeout_ms: 5000
        interval_ms: 2000
        registers:
          - key: "temperature"
            device_id: 1
            function: 3
            address: 0
            quantity: 1
            type: "float"
            scale: 0.1
            tags:
              description: "温度传感器"
          - key: "humidity"
            device_id: 1
            function: 3
            address: 1
            quantity: 1
            type: "float"
            scale: 0.1
            tags:
              description: "湿度传感器"
          - key: "pressure"
            device_id: 1
            function: 3
            address: 2
            quantity: 1
            type: "float"
            scale: 1.0
            tags:
              description: "压力传感器"
          - key: "status"
            device_id: 1
            function: 1
            address: 0
            quantity: 1
            type: "bool"
            tags:
              description: "设备状态"

northbound:
  sinks:
    - name: "mqtt-cloud"
      type: "mqtt"
      config:
        name: "mqtt-cloud"
        type: "mqtt"
        batch_size: 10
        buffer_size: 1000
        tags:
          gateway: "gateway-001"
          region: "east"
          source: "modbus-sidecar"
        params:
          broker: "tcp://192.168.2.71:1883"
          client_id: "gateway-001"
          topic_tpl: "iot/data/%s/%s"
          qos: 1
          retained: false

rule_engine:
  enabled: false
  rules: []

web_ui:
  enabled: true
  port: 8081
  auth:
    jwt_secret: "your-secret-key-change-in-production"
    token_duration: "24h"
    refresh_duration: "168h"
    max_login_attempts: 5
    lockout_duration: "15m"
    enable_two_factor: false
    session_timeout: "30m"
    password_min_length: 6
    bcrypt_cost: 10

database:
  sqlite:
    path: "./data/auth.db"

rules:
  dir: "./rules"
