gateway:
  id: "gateway-metrics-test"
  http_port: 8080
  log_level: "debug"
  nats_url: "embedded"
  plugins_dir: "./plugins"

southbound:
  adapters:
    - name: "test-mock"
      type: "mock"
      enabled: true
      config:
        device_id: "metrics-test-device"
        interval_ms: 1000
        points:
          - key: "temperature"
            min: 20.0
            max: 30.0
            type: "float"
            variance: 0.1
          - key: "humidity"
            min: 40.0
            max: 80.0
            type: "float"
            variance: 0.1

northbound:
  sinks:
    - name: "console-output"
      type: "console"
      enabled: true
      config:
        format: "json"
        batch_size: 5
        buffer_size: 100

rule_engine:
  enabled: false

web_ui:
  enabled: true
  port: 8081
  auth:
    jwt_secret: "test-secret"
    token_duration: "24h"

database:
  sqlite:
    path: "./data/auth.db"