gateway:
  id: "rule-engine-test"
  http_port: 8080
  log_level: "info"
  nats_url: "embedded"
  plugins_dir: "./plugins"

# 规则引擎配置
rule_engine:
  enabled: true
  rules_dir: "./data/rules"
  subject: "iot.data.>"
  rules:
    - id: "temp_10point_avg"
      name: "温度10点移动平均值"
      description: "计算每个温度传感器的10点移动平均值"
      enabled: true
      priority: 10
      conditions:
        type: "simple"
        field: "key"
        operator: "regex"
        value: ".*temperature$"
      actions:
        - type: "aggregate"
          config:
            window_type: "count"
            size: 10
            functions: ["avg"]
            group_by: ["key", "device_id"]
            output_key: "{{.Key}}_avg"
            forward: true

# 简化的北向连接器配置
northbound:
  sinks:
    - name: "console"
      type: "console"
      config:
        name: "console"
        format: "json"
        enable_timestamp: true
        enable_colors: false

# 不启用南向适配器，只测试规则引擎
southbound:
  adapters: [] 