# 适配器功能一致性测试配置
gateway:
  log_level: "info"
  nats_url: "embedded"
  enable_embedded_nats: true
  embedded_nats_port: 4222
  api_port: 8081
  web_port: 8080
  plugins_dir: "./plugins"

southbound:
  adapters:
    # 内置Mock适配器 - 用于对比测试
    - name: "builtin-mock"
      type: "mock"
      config:
        name: "builtin-mock"
        device_id: "builtin-device"
        interval_ms: 3000
        points:
          - key: "temperature"
            min: 20.0
            max: 30.0
            type: "float"
            variance: 0.1
          - key: "pressure"
            min: 1000
            max: 1100
            type: "int"
            variance: 0.05
          - key: "active"
            type: "bool" 
            constant: true

    # 内置Modbus适配器 - 如果有Modbus设备可以测试
    # - name: "builtin-modbus"
    #   type: "modbus"
    #   config:
    #     name: "builtin-modbus"
    #     mode: "tcp"
    #     address: "127.0.0.1:502"
    #     timeout_ms: 5000
    #     interval_ms: 4000
    #     registers:
    #       - key: "holding_reg_1"
    #         device_id: 1
    #         function: 3
    #         address: 0
    #         quantity: 1
    #         type: "float"
    #         scale: 0.1

northbound:
  sinks:
    - name: "comparison-console"
      type: "console"
      config:
        name: "comparison-console"
        batch_size: 1
        buffer_size: 100
        params:
          format: "json"
          prefix: "[COMPARISON]"