gateway:
  id: "gateway-modbus-test"
  http_port: 8081
  log_level: "debug"
  nats_url: "embedded"
  plugins_dir: "./plugins"

southbound:
  adapters:
    - name: "modbus-sensor-1"
      type: "modbus"
      config:
        mode: "tcp"
        address: "127.0.0.1:502"
        timeout_ms: 5000
        interval_ms: 3000
        registers:
          - key: "temperature_1"
            device_id: 1
            function: 3
            address: 0
            quantity: 1
            type: "float"
            scale: 0.1
            tags:
              description: "设备1温度传感器"
              device: "device1"
          - key: "humidity_1"
            device_id: 1
            function: 3
            address: 1
            quantity: 1
            type: "float"
            scale: 0.1
            tags:
              description: "设备1湿度传感器"
              device: "device1"
          - key: "pressure_1"
            device_id: 1
            function: 3
            address: 2
            quantity: 1
            type: "float"
            scale: 1
            tags:
              description: "设备1压力传感器"
              device: "device1"
          - key: "status_1"
            device_id: 1
            function: 1
            address: 0
            quantity: 1
            type: "bool"
            tags:
              description: "设备1状态"
              device: "device1"
    - name: "modbus-sensor-2"
      type: "modbus"
      config:
        mode: "tcp"
        address: "127.0.0.1:502"
        timeout_ms: 5000
        interval_ms: 3000
        registers:
          - key: "temperature_2"
            device_id: 2
            function: 3
            address: 0
            quantity: 1
            type: "float"
            scale: 0.1
            tags:
              description: "设备2温度传感器"
              device: "device2"
          - key: "humidity_2"
            device_id: 2
            function: 3
            address: 1
            quantity: 1
            type: "float"
            scale: 0.1
            tags:
              description: "设备2湿度传感器"
              device: "device2"
          - key: "pressure_2"
            device_id: 2
            function: 3
            address: 2
            quantity: 1
            type: "float"
            scale: 1
            tags:
              description: "设备2压力传感器"
              device: "device2"
          - key: "status_2"
            device_id: 2
            function: 1
            address: 0
            quantity: 1
            type: "bool"
            tags:
              description: "设备2状态"
              device: "device2"

northbound:
  sinks:
    - name: "console-output"
      type: "console"
      config:
        format: "json"
        level: "info"
    - name: "nats-publisher"
      type: "jetstream"
      config:
        name: "nats-publisher"
        batch_size: 1
        buffer_size: 100
        tags:
          source: "modbus-sidecar"
        params:
          url: "nats://127.0.0.1:4222"
          stream_name: "iot_data"
          subject: "iot.data.modbus"
          max_age: 86400000000000
          max_bytes: 1073741824
          replicas: 1

rule_engine:
  enabled: false

web_ui:
  enabled: false 