gateway:
  log_level: "debug"
  jetstream: true
  store_dir: "c:/projects/IoT Gateway/data/jetstream"
  # plugins_dir: "c:/projects/IoT Gateway/plugins"
  nats_url: "embedded"
  plugins_dir: "./plugins"

southbound:
  adapters:
    - name: "mock-sensor"
      type: "mock"
      config:
        interval_ms: 2000
        points:
          - key: "temperature"
            type: "float"
            min: 20.0
            max: 30.0
            tags:
              description: "模拟温度传感器"
          - key: "humidity"
            type: "float"
            min: 40.0
            max: 60.0
            tags:
              description: "模拟湿度传感器"
          - key: "pressure"
            type: "float"
            min: 980.0
            max: 1020.0
            tags:
              description: "模拟压力传感器"
          - key: "status"
            type: "bool"
            tags:
              description: "模拟状态传感器"

northbound:
  sinks:
    - name: "console"
      type: "console"
      config:
        pretty: true
